{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "dcba5626-3787-4561-b36c-41df20907c6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m2024-11-24 14:20:35.785\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36m<module>\u001b[0m:\u001b[36m292\u001b[0m - \u001b[1mRunning dash\u001b[0m\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1bb38bfe1e0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---------------------------------------------------------------------------\n",
      "gaierror                                  Traceback (most recent call last)\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connection.py:199, in HTTPConnection._new_conn(\n",
      "    self=<urllib3.connection.HTTPConnection object>\n",
      ")\n",
      "    198 try:\n",
      "--> 199     sock = connection.create_connection(\n",
      "        connection = <module 'urllib3.util.connection' from 'C:\\\\Users\\\\DELL\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python312\\\\venvs\\\\semana5_DSA_MIAD_DashEquipo\\\\Lib\\\\site-packages\\\\urllib3\\\\util\\\\connection.py'>\n",
      "        (self._dns_host, self.port) = ('none', 8001)\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "        self.port = 8001\n",
      "        self._dns_host = 'none'\n",
      "        self.timeout = None\n",
      "        self.source_address = None\n",
      "        self.socket_options = [(6, 1, 1)]\n",
      "    200         (self._dns_host, self.port),\n",
      "    201         self.timeout,\n",
      "    202         source_address=self.source_address,\n",
      "    203         socket_options=self.socket_options,\n",
      "    204     )\n",
      "    205 except socket.gaierror as e:\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\util\\connection.py:60, in create_connection(\n",
      "    address=('none', 8001),\n",
      "    timeout=None,\n",
      "    source_address=None,\n",
      "    socket_options=[(6, 1, 1)]\n",
      ")\n",
      "     58     raise LocationParseError(f\"'{host}', label empty or too long\") from None\n",
      "---> 60 for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n",
      "        family = <AddressFamily.AF_UNSPEC: 0>\n",
      "        host = 'none'\n",
      "        port = 8001\n",
      "        socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>\n",
      "     61     af, socktype, proto, canonname, sa = res\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py:976, in getaddrinfo(\n",
      "    host='none',\n",
      "    port=8001,\n",
      "    family=<AddressFamily.AF_UNSPEC: 0>,\n",
      "    type=<SocketKind.SOCK_STREAM: 1>,\n",
      "    proto=0,\n",
      "    flags=0\n",
      ")\n",
      "    975 addrlist = []\n",
      "--> 976 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "        host = 'none'\n",
      "        port = 8001\n",
      "        family = <AddressFamily.AF_UNSPEC: 0>\n",
      "        type = <SocketKind.SOCK_STREAM: 1>\n",
      "        proto = 0\n",
      "        flags = 0\n",
      "    977     af, socktype, proto, canonname, sa = res\n",
      "\n",
      "gaierror: [Errno 11001] getaddrinfo failed\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "NameResolutionError                       Traceback (most recent call last)\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connectionpool.py:789, in HTTPConnectionPool.urlopen(\n",
      "    self=<urllib3.connectionpool.HTTPConnectionPool object>,\n",
      "    method='POST',\n",
      "    url='/api/v1/predict',\n",
      "    body='{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}',\n",
      "    headers={'User-Agent': 'python-requests/2.32.3', 'Accept...pe': 'application/json', 'Content-Length': '242'},\n",
      "    retries=Retry(total=0, connect=None, read=False, redirect=None, status=None),\n",
      "    redirect=False,\n",
      "    assert_same_host=False,\n",
      "    timeout=Timeout(connect=None, read=None, total=None),\n",
      "    pool_timeout=None,\n",
      "    release_conn=False,\n",
      "    chunked=False,\n",
      "    body_pos=None,\n",
      "    preload_content=False,\n",
      "    decode_content=False,\n",
      "    **response_kw={}\n",
      ")\n",
      "    788 # Make the request on the HTTPConnection object\n",
      "--> 789 response = self._make_request(\n",
      "        self = <urllib3.connectionpool.HTTPConnectionPool object at 0x000001BB38CB77D0>\n",
      "        conn = None\n",
      "        method = 'POST'\n",
      "        url = '/api/v1/predict'\n",
      "        timeout_obj = Timeout(connect=None, read=None, total=None)\n",
      "        body = '{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinine_phosphokinase\": 155, \"diabetes\": 0, \"ejection_fraction\": 25, \"high_blood_pressure\": 0, \"platelets\": 258000, \"serum_creatinine\": 258000, \"serum_sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}'\n",
      "        headers = {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Content-Length': '242'}\n",
      "        chunked = False\n",
      "        retries = Retry(total=0, connect=None, read=False, redirect=None, status=None)\n",
      "        response_conn = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "        preload_content = False\n",
      "        decode_content = False\n",
      "        response_kw = {}\n",
      "    790     conn,\n",
      "    791     method,\n",
      "    792     url,\n",
      "    793     timeout=timeout_obj,\n",
      "    794     body=body,\n",
      "    795     headers=headers,\n",
      "    796     chunked=chunked,\n",
      "    797     retries=retries,\n",
      "    798     response_conn=response_conn,\n",
      "    799     preload_content=preload_content,\n",
      "    800     decode_content=decode_content,\n",
      "    801     **response_kw,\n",
      "    802 )\n",
      "    804 # Everything went great!\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connectionpool.py:495, in HTTPConnectionPool._make_request(\n",
      "    self=<urllib3.connectionpool.HTTPConnectionPool object>,\n",
      "    conn=<urllib3.connection.HTTPConnection object>,\n",
      "    method='POST',\n",
      "    url='/api/v1/predict',\n",
      "    body='{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}',\n",
      "    headers={'User-Agent': 'python-requests/2.32.3', 'Accept...pe': 'application/json', 'Content-Length': '242'},\n",
      "    retries=Retry(total=0, connect=None, read=False, redirect=None, status=None),\n",
      "    timeout=Timeout(connect=None, read=None, total=None),\n",
      "    chunked=False,\n",
      "    response_conn=<urllib3.connection.HTTPConnection object>,\n",
      "    preload_content=False,\n",
      "    decode_content=False,\n",
      "    enforce_content_length=True\n",
      ")\n",
      "    494 try:\n",
      "--> 495     conn.request(\n",
      "        conn = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "        method = 'POST'\n",
      "        url = '/api/v1/predict'\n",
      "        body = '{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinine_phosphokinase\": 155, \"diabetes\": 0, \"ejection_fraction\": 25, \"high_blood_pressure\": 0, \"platelets\": 258000, \"serum_creatinine\": 258000, \"serum_sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}'\n",
      "        headers = {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Content-Length': '242'}\n",
      "        chunked = False\n",
      "        preload_content = False\n",
      "        decode_content = False\n",
      "        enforce_content_length = True\n",
      "    496         method,\n",
      "    497         url,\n",
      "    498         body=body,\n",
      "    499         headers=headers,\n",
      "    500         chunked=chunked,\n",
      "    501         preload_content=preload_content,\n",
      "    502         decode_content=decode_content,\n",
      "    503         enforce_content_length=enforce_content_length,\n",
      "    504     )\n",
      "    506 # We are swallowing BrokenPipeError (errno.EPIPE) since the server is\n",
      "    507 # legitimately able to close the connection after sending a valid response.\n",
      "    508 # With this behaviour, the received response is still readable.\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connection.py:441, in HTTPConnection.request(\n",
      "    self=<urllib3.connection.HTTPConnection object>,\n",
      "    method='POST',\n",
      "    url='/api/v1/predict',\n",
      "    body='{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}',\n",
      "    headers={'User-Agent': 'python-requests/2.32.3', 'Accept...pe': 'application/json', 'Content-Length': '242'},\n",
      "    chunked=False,\n",
      "    preload_content=False,\n",
      "    decode_content=False,\n",
      "    enforce_content_length=True\n",
      ")\n",
      "    440     self.putheader(header, value)\n",
      "--> 441 self.endheaders()\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "    443 # If we're given a body we start sending that in chunks.\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\http\\client.py:1331, in HTTPConnection.endheaders(\n",
      "    self=<urllib3.connection.HTTPConnection object>,\n",
      "    message_body=None,\n",
      "    encode_chunked=False\n",
      ")\n",
      "   1330     raise CannotSendHeader()\n",
      "-> 1331 self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "        message_body = None\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "        encode_chunked = False\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\http\\client.py:1091, in HTTPConnection._send_output(\n",
      "    self=<urllib3.connection.HTTPConnection object>,\n",
      "    message_body=None,\n",
      "    encode_chunked=False\n",
      ")\n",
      "   1090 del self._buffer[:]\n",
      "-> 1091 self.send(msg)\n",
      "        msg = b'POST /api/v1/predict HTTP/1.1\\r\\nHost: none:8001\\r\\nUser-Agent: python-requests/2.32.3\\r\\nAccept-Encoding: gzip, deflate\\r\\naccept: application/json\\r\\nConnection: keep-alive\\r\\nContent-Type: application/json\\r\\nContent-Length: 242\\r\\n\\r\\n'\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "   1093 if message_body is not None:\n",
      "   1094 \n",
      "   1095     # create a consistent interface to message_body\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\http\\client.py:1035, in HTTPConnection.send(\n",
      "    self=<urllib3.connection.HTTPConnection object>,\n",
      "    data=b'POST /api/v1/predict HTTP/1.1\\r\\nHost: none:80... application/json\\r\\nContent-Length: 242\\r\\n\\r\\n'\n",
      ")\n",
      "   1034 if self.auto_open:\n",
      "-> 1035     self.connect()\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "   1036 else:\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connection.py:279, in HTTPConnection.connect(\n",
      "    self=<urllib3.connection.HTTPConnection object>\n",
      ")\n",
      "    278 def connect(self) -> None:\n",
      "--> 279     self.sock = self._new_conn()\n",
      "        self.sock = None\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "    280     if self._tunnel_host:\n",
      "    281         # If we're tunneling it means we're connected to our proxy.\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connection.py:206, in HTTPConnection._new_conn(\n",
      "    self=<urllib3.connection.HTTPConnection object>\n",
      ")\n",
      "    205 except socket.gaierror as e:\n",
      "--> 206     raise NameResolutionError(self.host, self, e) from e\n",
      "        self = <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>\n",
      "    207 except SocketTimeout as e:\n",
      "\n",
      "NameResolutionError: <urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "MaxRetryError                             Traceback (most recent call last)\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\requests\\adapters.py:667, in HTTPAdapter.send(\n",
      "    self=<requests.adapters.HTTPAdapter object>,\n",
      "    request=<PreparedRequest [POST]>,\n",
      "    stream=False,\n",
      "    timeout=Timeout(connect=None, read=None, total=None),\n",
      "    verify=True,\n",
      "    cert=None,\n",
      "    proxies=OrderedDict()\n",
      ")\n",
      "    666 try:\n",
      "--> 667     resp = conn.urlopen(\n",
      "        conn = <urllib3.connectionpool.HTTPConnectionPool object at 0x000001BB38CB77D0>\n",
      "        request = <PreparedRequest [POST]>\n",
      "        request.method = 'POST'\n",
      "        url = '/api/v1/predict'\n",
      "        request.body = '{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinine_phosphokinase\": 155, \"diabetes\": 0, \"ejection_fraction\": 25, \"high_blood_pressure\": 0, \"platelets\": 258000, \"serum_creatinine\": 258000, \"serum_sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}'\n",
      "        request.headers = {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Content-Length': '242'}\n",
      "        self = <requests.adapters.HTTPAdapter object at 0x000001BB38CB76B0>\n",
      "        self.max_retries = Retry(total=0, connect=None, read=False, redirect=None, status=None)\n",
      "        timeout = Timeout(connect=None, read=None, total=None)\n",
      "        chunked = False\n",
      "    668         method=request.method,\n",
      "    669         url=url,\n",
      "    670         body=request.body,\n",
      "    671         headers=request.headers,\n",
      "    672         redirect=False,\n",
      "    673         assert_same_host=False,\n",
      "    674         preload_content=False,\n",
      "    675         decode_content=False,\n",
      "    676         retries=self.max_retries,\n",
      "    677         timeout=timeout,\n",
      "    678         chunked=chunked,\n",
      "    679     )\n",
      "    681 except (ProtocolError, OSError) as err:\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\connectionpool.py:843, in HTTPConnectionPool.urlopen(\n",
      "    self=<urllib3.connectionpool.HTTPConnectionPool object>,\n",
      "    method='POST',\n",
      "    url='/api/v1/predict',\n",
      "    body='{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}',\n",
      "    headers={'User-Agent': 'python-requests/2.32.3', 'Accept...pe': 'application/json', 'Content-Length': '242'},\n",
      "    retries=Retry(total=0, connect=None, read=False, redirect=None, status=None),\n",
      "    redirect=False,\n",
      "    assert_same_host=False,\n",
      "    timeout=Timeout(connect=None, read=None, total=None),\n",
      "    pool_timeout=None,\n",
      "    release_conn=False,\n",
      "    chunked=False,\n",
      "    body_pos=None,\n",
      "    preload_content=False,\n",
      "    decode_content=False,\n",
      "    **response_kw={}\n",
      ")\n",
      "    841     new_e = ProtocolError(\"Connection aborted.\", new_e)\n",
      "--> 843 retries = retries.increment(\n",
      "        retries = Retry(total=0, connect=None, read=False, redirect=None, status=None)\n",
      "        url = '/api/v1/predict'\n",
      "        method = 'POST'\n",
      "        self = <urllib3.connectionpool.HTTPConnectionPool object at 0x000001BB38CB77D0>\n",
      "        new_e = NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)\")\n",
      "    844     method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]\n",
      "    845 )\n",
      "    846 retries.sleep()\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\urllib3\\util\\retry.py:519, in Retry.increment(\n",
      "    self=Retry(total=0, connect=None, read=False, redirect=None, status=None),\n",
      "    method='POST',\n",
      "    url='/api/v1/predict',\n",
      "    response=None,\n",
      "    error=NameResolutionError(\"<urllib3.connection.HTTPCon...solve 'none' ([Errno 11001] getaddrinfo failed)\"),\n",
      "    _pool=<urllib3.connectionpool.HTTPConnectionPool object>,\n",
      "    _stacktrace=<traceback object>\n",
      ")\n",
      "    518     reason = error or ResponseError(cause)\n",
      "--> 519     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n",
      "        reason = NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)\")\n",
      "        url = '/api/v1/predict'\n",
      "        _pool = <urllib3.connectionpool.HTTPConnectionPool object at 0x000001BB38CB77D0>\n",
      "    521 log.debug(\"Incremented Retry for (url='%s'): %r\", url, new_retry)\n",
      "\n",
      "MaxRetryError: HTTPConnectionPool(host='none', port=8001): Max retries exceeded with url: /api/v1/predict (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)\"))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "ConnectionError                           Traceback (most recent call last)\n",
      "File ~\\OneDrive - Universidad de los andes\\Escritorio\\docker-dash\\app\\app.py:211, in update_output_div(\n",
      "    edad='50',\n",
      "    anemia='No',\n",
      "    creatinine_phosphokinase='155',\n",
      "    diabetes='No',\n",
      "    ejection_fraction='25',\n",
      "    high_blood_pressure='No',\n",
      "    platelets='258000',\n",
      "    serum_creatinine='0',\n",
      "    serum_sodium='13',\n",
      "    sex='Mujer',\n",
      "    smoking='No',\n",
      "    time='5'\n",
      ")\n",
      "    208 headers =  {\"Content-Type\":\"application/json\", \"accept\": \"application/json\"}\n",
      "    210 # POST call to the API\n",
      "--> 211 response = requests.post(api_url, data=json.dumps(myreq), headers=headers)\n",
      "        myreq = {'inputs': [{'age': 50, 'anaemia': 0, 'creatinine_phosphokinase': 155, 'diabetes': 0, 'ejection_fraction': 25, 'high_blood_pressure': 0, 'platelets': 258000, 'serum_creatinine': 258000, 'serum_sodium': 13, 'sex': 0, 'smoking': 0, 'time': 5}]}\n",
      "        headers = {'Content-Type': 'application/json', 'accept': 'application/json'}\n",
      "        api_url = 'http://None:8001/api/v1/predict'\n",
      "    212 data = response.json()\n",
      "    213 logger.info(\"Response: {}\".format(data))\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\requests\\api.py:115, in post(\n",
      "    url='http://None:8001/api/v1/predict',\n",
      "    data='{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}',\n",
      "    json=None,\n",
      "    **kwargs={'headers': {'Content-Type': 'application/json', 'accept': 'application/json'}}\n",
      ")\n",
      "    103 def post(url, data=None, json=None, **kwargs):\n",
      "    104     r\"\"\"Sends a POST request.\n",
      "    105 \n",
      "    106     :param url: URL for the new :class:`Request` object.\n",
      "   (...)\n",
      "    112     :rtype: requests.Response\n",
      "    113     \"\"\"\n",
      "--> 115     return request(\"post\", url, data=data, json=json, **kwargs)\n",
      "        url = 'http://None:8001/api/v1/predict'\n",
      "        data = '{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinine_phosphokinase\": 155, \"diabetes\": 0, \"ejection_fraction\": 25, \"high_blood_pressure\": 0, \"platelets\": 258000, \"serum_creatinine\": 258000, \"serum_sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}'\n",
      "        json = None\n",
      "        kwargs = {'headers': {'Content-Type': 'application/json', 'accept': 'application/json'}}\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\requests\\api.py:59, in request(\n",
      "    method='post',\n",
      "    url='http://None:8001/api/v1/predict',\n",
      "    **kwargs={'data': '{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}', 'headers': {'Content-Type': 'application/json', 'accept': 'application/json'}, 'json': None}\n",
      ")\n",
      "     55 # By using the 'with' statement we are sure the session is closed, thus we\n",
      "     56 # avoid leaving sockets open which can trigger a ResourceWarning in some\n",
      "     57 # cases, and look like a memory leak in others.\n",
      "     58 with sessions.Session() as session:\n",
      "---> 59     return session.request(method=method, url=url, **kwargs)\n",
      "        session = <requests.sessions.Session object at 0x000001BB38BFFCB0>\n",
      "        method = 'post'\n",
      "        url = 'http://None:8001/api/v1/predict'\n",
      "        kwargs = {'data': '{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinine_phosphokinase\": 155, \"diabetes\": 0, \"ejection_fraction\": 25, \"high_blood_pressure\": 0, \"platelets\": 258000, \"serum_creatinine\": 258000, \"serum_sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}', 'json': None, 'headers': {'Content-Type': 'application/json', 'accept': 'application/json'}}\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\requests\\sessions.py:589, in Session.request(\n",
      "    self=<requests.sessions.Session object>,\n",
      "    method='post',\n",
      "    url='http://None:8001/api/v1/predict',\n",
      "    params=None,\n",
      "    data='{\"inputs\": [{\"age\": 50, \"anaemia\": 0, \"creatinin...sodium\": 13, \"sex\": 0, \"smoking\": 0, \"time\": 5}]}',\n",
      "    headers={'Content-Type': 'application/json', 'accept': 'application/json'},\n",
      "    cookies=None,\n",
      "    files=None,\n",
      "    auth=None,\n",
      "    timeout=None,\n",
      "    allow_redirects=True,\n",
      "    proxies={},\n",
      "    hooks=None,\n",
      "    stream=None,\n",
      "    verify=None,\n",
      "    cert=None,\n",
      "    json=None\n",
      ")\n",
      "    584 send_kwargs = {\n",
      "    585     \"timeout\": timeout,\n",
      "    586     \"allow_redirects\": allow_redirects,\n",
      "    587 }\n",
      "    588 send_kwargs.update(settings)\n",
      "--> 589 resp = self.send(prep, **send_kwargs)\n",
      "        prep = <PreparedRequest [POST]>\n",
      "        send_kwargs = {'timeout': None, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}\n",
      "        self = <requests.sessions.Session object at 0x000001BB38BFFCB0>\n",
      "    591 return resp\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\requests\\sessions.py:703, in Session.send(\n",
      "    self=<requests.sessions.Session object>,\n",
      "    request=<PreparedRequest [POST]>,\n",
      "    **kwargs={'cert': None, 'proxies': OrderedDict(), 'stream': False, 'timeout': None, 'verify': True}\n",
      ")\n",
      "    700 start = preferred_clock()\n",
      "    702 # Send the request\n",
      "--> 703 r = adapter.send(request, **kwargs)\n",
      "        adapter = <requests.adapters.HTTPAdapter object at 0x000001BB38CB76B0>\n",
      "        kwargs = {'timeout': None, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}\n",
      "        request = <PreparedRequest [POST]>\n",
      "    705 # Total elapsed time of the request (approximately)\n",
      "    706 elapsed = preferred_clock() - start\n",
      "\n",
      "File ~\\AppData\\Local\\Programs\\Python\\Python312\\venvs\\semana5_DSA_MIAD_DashEquipo\\Lib\\site-packages\\requests\\adapters.py:700, in HTTPAdapter.send(\n",
      "    self=<requests.adapters.HTTPAdapter object>,\n",
      "    request=<PreparedRequest [POST]>,\n",
      "    stream=False,\n",
      "    timeout=Timeout(connect=None, read=None, total=None),\n",
      "    verify=True,\n",
      "    cert=None,\n",
      "    proxies=OrderedDict()\n",
      ")\n",
      "    696     if isinstance(e.reason, _SSLError):\n",
      "    697         # This branch is for urllib3 v1.22 and later.\n",
      "    698         raise SSLError(e, request=request)\n",
      "--> 700     raise ConnectionError(e, request=request)\n",
      "        request = <PreparedRequest [POST]>\n",
      "    702 except ClosedPoolError as e:\n",
      "    703     raise ConnectionError(e, request=request)\n",
      "\n",
      "ConnectionError: HTTPConnectionPool(host='none', port=8001): Max retries exceeded with url: /api/v1/predict (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x000001BB38CB71A0>: Failed to resolve 'none' ([Errno 11001] getaddrinfo failed)\"))\n",
      "\n",
      "---------------------------------------------------------------------------\n",
      "KeyError                                  Traceback (most recent call last)\n",
      "File ~\\OneDrive - Universidad de los andes\\Escritorio\\docker-dash\\app\\app.py:194, in update_output_div(\n",
      "    edad='50',\n",
      "    anemia=None,\n",
      "    creatinine_phosphokinase='155',\n",
      "    diabetes='No',\n",
      "    ejection_fraction='25',\n",
      "    high_blood_pressure='No',\n",
      "    platelets='258000',\n",
      "    serum_creatinine='0',\n",
      "    serum_sodium='13',\n",
      "    sex='Mujer',\n",
      "    smoking='No',\n",
      "    time='5'\n",
      ")\n",
      "    173 @app.callback(\n",
      "    174     Output(component_id='resultado', component_property='children'),\n",
      "    175     [Input(component_id='edad', component_property='value'), \n",
      "   (...)\n",
      "    188 \n",
      "    189 def update_output_div(edad, anemia, creatinine_phosphokinase, diabetes, ejection_fraction, high_blood_pressure, platelets, serum_creatinine, serum_sodium, sex, smoking, time):\n",
      "    190     myreq = {\n",
      "    191         \"inputs\": [\n",
      "    192             {\n",
      "    193                 \"age\": int(edad),\n",
      "--> 194                 \"anaemia\": map_si_no[anemia],\n",
      "        int(edad) = 50\n",
      "        edad = '50'\n",
      "        map_si_no = {'No': 0, 'Sí': 1}\n",
      "        anemia = None\n",
      "        int(creatinine_phosphokinase) = 155\n",
      "        creatinine_phosphokinase = '155'\n",
      "        map_si_no[diabetes] = 0\n",
      "        diabetes = 'No'\n",
      "        int(ejection_fraction) = 25\n",
      "        ejection_fraction = '25'\n",
      "        map_si_no[high_blood_pressure] = 0\n",
      "        high_blood_pressure = 'No'\n",
      "        int(platelets) = 258000\n",
      "        platelets = '258000'\n",
      "        int(serum_sodium) = 13\n",
      "        serum_sodium = '13'\n",
      "        map_hombre_mujer[sex] = 0\n",
      "        map_hombre_mujer = {'Mujer': 0, 'Hombre': 1}\n",
      "        sex = 'Mujer'\n",
      "        map_si_no[smoking] = 0\n",
      "        smoking = 'No'\n",
      "        int(time) = 5\n",
      "        time = '5'\n",
      "    195                 \"creatinine_phosphokinase\": int(creatinine_phosphokinase),\n",
      "    196                 \"diabetes\": map_si_no[diabetes],\n",
      "    197                 \"ejection_fraction\": int(ejection_fraction),\n",
      "    198                 \"high_blood_pressure\": map_si_no[high_blood_pressure],\n",
      "    199                 \"platelets\": int(platelets),\n",
      "    200                 \"serum_creatinine\": int(platelets),\n",
      "    201                 \"serum_sodium\": int(serum_sodium),\n",
      "    202                 \"sex\": map_hombre_mujer[sex],\n",
      "    203                 \"smoking\": map_si_no[smoking],\n",
      "    204                 \"time\": int(time)\n",
      "    205             }\n",
      "    206         ]\n",
      "    207       }\n",
      "    208     headers =  {\"Content-Type\":\"application/json\", \"accept\": \"application/json\"}\n",
      "    210     # POST call to the API\n",
      "\n",
      "KeyError: None\n",
      "\n"
     ]
    }
   ],
   "source": [
    "%run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "97712e18-7c7b-48ef-a729-c59e3a5e7143",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88e07d9f-d562-4583-b906-c370936990f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "'No'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "6e957326-270e-43cb-accd-5737be9f15ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "map_si_no = {'No':0, 'Sí':1}\n",
    "map_hombre_mujer = {'Mujer':0, 'Hombre':1}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "ea685744-174c-4f51-ae93-10b1380bc7cc",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'str' object has no attribute 'map'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[23], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mNo\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmap\u001b[49m(map_si_no)\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'str' object has no attribute 'map'"
     ]
    }
   ],
   "source": [
    "'No'.map(map_si_no)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "e5c0749d-d7bf-41a5-a676-6ca918dc7d84",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "map_si_no['No']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "a601579e-6bc1-4fbf-a716-1ce43a9f272d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting loguru\n",
      "  Downloading loguru-0.7.2-py3-none-any.whl.metadata (23 kB)\n",
      "Requirement already satisfied: colorama>=0.3.4 in c:\\users\\dell\\appdata\\local\\programs\\python\\python312\\venvs\\semana5_dsa_miad_dashequipo\\lib\\site-packages (from loguru) (0.4.6)\n",
      "Collecting win32-setctime>=1.0.0 (from loguru)\n",
      "  Downloading win32_setctime-1.1.0-py3-none-any.whl.metadata (2.3 kB)\n",
      "Downloading loguru-0.7.2-py3-none-any.whl (62 kB)\n",
      "Downloading win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)\n",
      "Installing collected packages: win32-setctime, loguru\n",
      "Successfully installed loguru-0.7.2 win32-setctime-1.1.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 24.2 -> 24.3.1\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install loguru "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
